BRANCH-41 add more souts
voitsel/GitHubTest pull request #10
Opened 2020-10-05 14:22 UTC by voitsel

with comment

2020-11-10 19:22 UTC, kara4k commented on src/main/java/NewClass.java
>          System.out.println("Test");
review comment on line 1

2020-11-10 19:25 UTC, kara4k requested changes

2020-11-10 19:25 UTC, kara4k commented on src/main/java/NewClass.java
> +        System.out.println("Test");
review comment on line 2

2020-11-10 19:25 UTC, kara4k commented on src/main/java/NewClass.java
> +        System.out.println("Test");
review comment 3

2020-11-10 19:56 UTC, voitsel commented
default comment

2020-11-10 21:17 UTC, kara4k approved these changes

2020-11-10 21:17 UTC, kara4k commented on src/main/java/NewClass.java
> +        System.out.println("Test");
one more

2020-11-10 21:19 UTC, kara4k commented on src/main/java/NewClass.java
>          System.out.println("Test");
approved

2020-11-10 21:19 UTC, kara4k approved these changes
Nice

2020-12-02 09:47 UTC, kara4k reviewed
aaaaa

2020-12-09 13:32 UTC, merged